#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
# autospec version: v10
# autospec commit: 5905be9
#
Name     : rng-tools
Version  : 6.17
Release  : 31
URL      : https://github.com/nhorman/rng-tools/archive/v6.17/rng-tools-6.17.tar.gz
Source0  : https://github.com/nhorman/rng-tools/archive/v6.17/rng-tools-6.17.tar.gz
Source1  : rngd.service
Summary  : Random number generator related utilities
Group    : Development/Tools
License  : GPL-2.0
Requires: rng-tools-bin = %{version}-%{release}
Requires: rng-tools-data = %{version}-%{release}
Requires: rng-tools-license = %{version}-%{release}
Requires: rng-tools-man = %{version}-%{release}
Requires: rng-tools-services = %{version}-%{release}
BuildRequires : curl-dev
BuildRequires : glibc-staticdev
BuildRequires : jansson-dev
BuildRequires : pkgconfig(libcap)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(openssl)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: trim.patch
Patch2: feed-more.patch

%description
This is a random number generator daemon. It monitors a hardware random number
generator, and supplies entropy from that to the system kernel's /dev/random
machinery.

%package autostart
Summary: autostart components for the rng-tools package.
Group: Default

%description autostart
autostart components for the rng-tools package.


%package bin
Summary: bin components for the rng-tools package.
Group: Binaries
Requires: rng-tools-data = %{version}-%{release}
Requires: rng-tools-license = %{version}-%{release}
Requires: rng-tools-services = %{version}-%{release}

%description bin
bin components for the rng-tools package.


%package data
Summary: data components for the rng-tools package.
Group: Data

%description data
data components for the rng-tools package.


%package license
Summary: license components for the rng-tools package.
Group: Default

%description license
license components for the rng-tools package.


%package man
Summary: man components for the rng-tools package.
Group: Default

%description man
man components for the rng-tools package.


%package services
Summary: services components for the rng-tools package.
Group: Systemd services
Requires: systemd

%description services
services components for the rng-tools package.


%prep
%setup -q -n rng-tools-6.17
cd %{_builddir}/rng-tools-6.17
%patch -P 1 -p1
%patch -P 2 -p1
pushd ..
cp -a rng-tools-6.17 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1716762332
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%autogen --disable-static --without-nistbeacon \
--without-pkcs11 \
--without-rtlsdr
make  %{?_smp_mflags}

pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%autogen --disable-static --without-nistbeacon \
--without-pkcs11 \
--without-rtlsdr
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :
cd ../buildavx2;
make %{?_smp_mflags} check || : || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1716762332
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/rng-tools
cp %{_builddir}/rng-tools-%{version}/COPYING %{buildroot}/usr/share/package-licenses/rng-tools/4cc77b90af91e615a64ae04893fdffa7939db84c || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/rngd.service
## install_append content
mkdir -p %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
ln -sf ../rngd.service %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/rngd.service
mkdir -p %{buildroot}/usr/share/clr-service-restart
ln -sf /usr/lib/systemd/system/rngd.service %{buildroot}/usr/share/clr-service-restart/rngd.service
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/rngd.service

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/randstat
/V3/usr/bin/rngd
/V3/usr/bin/rngtest
/usr/bin/randstat
/usr/bin/rngd
/usr/bin/rngtest

%files data
%defattr(-,root,root,-)
/usr/share/clr-service-restart/rngd.service

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/rng-tools/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/rngtest.1
/usr/share/man/man8/rngd.8

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/rngd.service
/usr/lib/systemd/system/rngd.service
