#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rng-tools
Version  : 5
Release  : 22
URL      : https://sourceforge.net/projects/gkernel/files/rng-tools/5/rng-tools-5.tar.gz
Source0  : https://sourceforge.net/projects/gkernel/files/rng-tools/5/rng-tools-5.tar.gz
Source1  : rngd.service
Summary  : Random number generator related utilities
Group    : Development/Tools
License  : GPL-2.0
Requires: rng-tools-bin = %{version}-%{release}
Requires: rng-tools-data = %{version}-%{release}
Requires: rng-tools-license = %{version}-%{release}
Requires: rng-tools-man = %{version}-%{release}
Requires: rng-tools-services = %{version}-%{release}
BuildRequires : glibc-staticdev
Patch1: trim.patch
Patch2: feed-more.patch

%description
This is a random number generator daemon.
It monitors a hardware random number generator, and supplies entropy
from that to the system kernel's /dev/random machinery.

%package autostart
Summary: autostart components for the rng-tools package.
Group: Default

%description autostart
autostart components for the rng-tools package.


%package bin
Summary: bin components for the rng-tools package.
Group: Binaries
Requires: rng-tools-data = %{version}-%{release}
Requires: rng-tools-license = %{version}-%{release}
Requires: rng-tools-services = %{version}-%{release}

%description bin
bin components for the rng-tools package.


%package data
Summary: data components for the rng-tools package.
Group: Data

%description data
data components for the rng-tools package.


%package license
Summary: license components for the rng-tools package.
Group: Default

%description license
license components for the rng-tools package.


%package man
Summary: man components for the rng-tools package.
Group: Default

%description man
man components for the rng-tools package.


%package services
Summary: services components for the rng-tools package.
Group: Systemd services

%description services
services components for the rng-tools package.


%prep
%setup -q -n rng-tools-5
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1559831097
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition "
%configure --disable-static
make  %{?_smp_mflags} CFLAGS="$CFLAGS -static"

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1559831097
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/rng-tools
cp COPYING %{buildroot}/usr/share/package-licenses/rng-tools/COPYING
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/rngd.service
## install_append content
mkdir -p %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
ln -sf ../rngd.service %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/rngd.service
mkdir -p %{buildroot}/usr/share/clr-service-restart
ln -sf /usr/lib/systemd/system/rngd.service %{buildroot}/usr/share/clr-service-restart/rngd.service
## install_append end

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/rngd.service

%files bin
%defattr(-,root,root,-)
/usr/bin/rngd
/usr/bin/rngtest

%files data
%defattr(-,root,root,-)
/usr/share/clr-service-restart/rngd.service

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/rng-tools/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/rngtest.1
/usr/share/man/man8/rngd.8

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/rngd.service
/usr/lib/systemd/system/rngd.service
